###
GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDc5NzMxMTJ9.Zr-G1p0HH8QQKCnBrwbo4QmgmYjmNWe_63rkcCzawCk

###
GET http://localhost:3000/products/1.json

###
POST http://localhost:3000/products.json
content-type: application/json

{
  "input_name": "cake",
  "input_price": 23,
  "input_image_url": "https://cdn.shopify.com/s/files/1/1249/3023/products/FineTOUGHOKGloveIndigoWhite.png?v=1637343200",
  "input_description": "fattening delicious cake"
}

###
PATCH http://localhost:3000/products/3.json
content-type: application/json

{
  "input_supplier_id": 2
}

###
DELETE http://localhost:3000/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgxNDIyODN9.X2IT-ioktFqA1URmOZ1mlbpite270XYmcc8Xwf9o-FQ

###
GET http://localhost:3000/suppliers.json

###
GET http://localhost:3000/suppliers/2.json

###
POST http://localhost:3000/suppliers.json

###
PATCH http://localhost:3000/suppliers/2.json

###
DELETE http://localhost:3000/suppliers.json

###
POST http://localhost:3000/users
content-type: application/json

{
  "name": "Ben",
  "email": "ben@test.com",
  "password": "password",
  "password_confirmation": "password"
}

###
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "ben@test.com",
  "password": "password"
}

###
POST http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgxNDIyODN9.X2IT-ioktFqA1URmOZ1mlbpite270XYmcc8Xwf9o-FQ
content-type: application/json

{
  "user_id": 1,
  "product_id": 2,
  "quantity": 2
}

###
GET http://localhost:3000/orders/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDgwNTYyNTZ9.jwmHooN5WI3FLW8Q_cnO1cRxdoaTh7zVbXydFCHGxfA


###
GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDgwNTYyNTZ9.jwmHooN5WI3FLW8Q_cnO1cRxdoaTh7zVbXydFCHGxfA

###
POST http://localhost:3000/carted_products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDgzMjIwNjl9.LstTJeS97Zh08nDlJOg71bto78cD1dUe-tTKsIiMjJo
content-type: Application/json

{
  "product_id": 9,
  "quantity": 2
}

###
GET http://localhost:3000/carted_products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgzMjI4OTF9.ReQDP3_2apeSy60kfoyzjSxmj4KxIC9l2Xo4kB-CQEY