@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDk4NzU0NzR9._avBQ4LmBV_5PsdsnvdwNC225Y1HhRdYXRUrRMO9UJ4

###
GET http://localhost:3000/products.json
Authorization: Bearer jwt

###
GET http://localhost:3000/products/2.json
Authorization: Bearer jwt

###
POST http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDk4NzU0NzR9._avBQ4LmBV_5PsdsnvdwNC225Y1HhRdYXRUrRMO9UJ4
content-type: application/json

{
  "input_name": "Hat",
  "input_price": 23,
  "input_description": "fattening delicious cake",
  "input_supplier_id": 2
}

###
PATCH http://localhost:3000/products/3.json
content-type: application/json

{
  "input_supplier_id": 2
}

###
DELETE http://localhost:3000/products/1
Authorization: Bearer jwt

###
GET http://localhost:3000/suppliers.json

###
GET http://localhost:3000/suppliers/2.json

###
POST http://localhost:3000/suppliers.json

###
PATCH http://localhost:3000/suppliers/2.json

###
DELETE http://localhost:3000/suppliers.json

###
POST http://localhost:3000/users
content-type: application/json

{
  "name": "Ben",
  "email": "ben@test.com",
  "password": "password",
  "password_confirmation": "password"
}

###
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "ben@test.com",
  "password": "password"
}

###
POST http://localhost:3000/orders
Authorization: Bearer jwt


###
GET http://localhost:3000/orders/16
Authorization: Bearer jwt


###
GET http://localhost:3000/orders
Authorization: Bearer jwt

###
POST http://localhost:3000/carted_products
Authorization: Bearer jwt
content-type: Application/json

{
  "product_id": 9,
  "quantity": 2
}

###
GET http://localhost:3000/carted_products
Authorization: Bearer jwt

###
DELETE http://localhost:3000/carted_products/15
Authorization: Bearer jwt